[tools]
bun = "1.3.6"
node = "lts"
jq = "latest"

[task_config]
dir = "{{ config_root }}"

[env]
'_'.path = { path = "./node_modules/.bin" }
STORYBOOK_ENABLE_CRASH_REPORTS = 1

[prepare]
bun.auto = true

[shell_alias]
mr = "mise run"
